apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    run: demo-example
spec:
  containers:
  - env:
    - name: BUCKET_NAME
      value: /tmp/demo
    - name: OBJECT_STORAGE_S3_TYPE
      value: local
    image: docker.io/zherman/demo:latest
    imagePullPolicy: Always
    name: demo-app
    ports:
    - containerPort: 3000
      protocol: TCP
