apiVersion: v1
kind: Pod
metadata:
  name: demo-app
spec:
  containers:
  - env:
    - name: BUCKET_NAME
      valueFrom:
            secretKeyRef:
              name: s3-binding
              key: bucketName

    - name: OBJECT_STORAGE_S3_TYPE
      value: gfs
    - name: BUCKET_ENDPOINT
      valueFrom:
            secretKeyRef:
              name: s3-binding
              key: bucketEndpoint
    - name: BUCKET_ID
      valueFrom:
            secretKeyRef:
              name: s3-binding
              key: bucketID

    - name: BUCKET_PWORD
      valueFrom:
           secretKeyRef:
             name: s3-binding
             key: bucketPword
    image: localhost:5000/demo-app:latest
    imagePullPolicy: Always
    name: demo-app
    ports:
    - containerPort: 3000
      protocol: TCP
