apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
subsets:
- addresses:
  - ip: 172.18.1.140
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 172.18.3.158
  ports:
  - port: 1
    protocol: TCP

