apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv   
spec:
  capacity:
    storage: 10Gi     
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: gluster-cluster 
    path: /gv0 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
