apiVersion: v1
kind: Pod
metadata:
  name: gluster-pod1
  labels:
    name: gluster-pod1   
spec:
  containers:
  - name: gluster-pod1
    image: nginx       
    ports:
    - name: web
      containerPort: 80
    securityContext:
      privileged: true
    volumeMounts:
    - name: gluster-vol1 
      mountPath: /usr/share/nginx/html 
      readOnly: false
  securityContext:
    supplementalGroups: [590]       
  volumes:
  - name: gluster-vol1   
    persistentVolumeClaim:
      claimName: gluster-claim  
