name: delete
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  push-operator:
    name: Build image
    runs-on: ubuntu-20.04
    steps:
    - name: home
      run: echo ~
